/*******************************************************************************
 * Copyright (c) The JETSCAPE Collaboration, 2018
 *
 * Modular, task-based framework for simulating all aspects of heavy-ion
 *collisions
 *
 * For the list of contributors see AUTHORS.
 *
 * Report issues at https://github.com/JETSCAPE/JETSCAPE/issues
 *
 * or via email to bugs.jetscape@gmail.com
 *
 * Distributed under the GNU General Public License 3.0 (GPLv3 or later).
 * See COPYING for details.
 ******************************************************************************/

#ifndef HARDPROCESS_H
#define HARDPROCESS_H

#include <vector>

#include "InitialState.h"
#include "JetClass.h"
#include "JetScapeModuleBase.h"

namespace Jetscape {

/**
 * @class HardProcess
 * @brief Interface for the hard scattering process in the JetScape framework.
 *
 * The HardProcess class defines the interface and base functionality
 * for simulating hard scattering events. It provides methods for
 * initialization, execution, clearing state, writing output, and handling event
 * metadata such as cross-sections and weights. Derived classes implement
 * specific physics modules such as Pythia-based event generators.
 */
class HardProcess : public JetScapeModuleBase {
 public:
  /**
   * @brief Default constructor.
   *
   * Creates a HardProcess physics task and sets the task ID as "HardProcess".
   */
  HardProcess();

  /**
   * @brief Destructor.
   *
   * Cleans up parton and hadron lists, disconnects signals, and finalizes
   * the task.
   */
  virtual ~HardProcess();

  /**
   * @brief Initialize the HardProcess module.
   *
   * Reads input parameters from the XML file under the `<Hard>` tag, retrieves
   * the InitialState module from JetScapeSignalManager, sets up printer
   * options, and initializes attached sub-tasks.
   */
  virtual void Init();

  /**
   * @brief Execute the HardProcess module.
   *
   * Runs attached tasks recursively via JetScapeTask::ExecuteTasks().
   */
  virtual void Exec();

  /**
   * @brief Clear the internal state.
   *
   * Erases all stored hard partons and hadrons from memory.
   */
  virtual void Clear();

  /**
   * @brief Write hard process data to output.
   *
   * @param w Weak pointer to a JetScapeWriter module.
   *
   * Outputs hard parton list and related metadata to the writer.
   */
  virtual void WriteTask(weak_ptr<JetScapeWriter> w);

  /**
   * @brief Collect header information for output.
   *
   * @param w Weak pointer to a JetScapeWriter module.
   *
   * Stores generated cross-sections, pt-hat, and event weights into
   * the output header.
   */
  virtual void CollectHeader(weak_ptr<JetScapeWriter> w);

  /** @brief Pointer to the InitialState module. */
  std::shared_ptr<InitialState> ini;

  /** @return Number of hard partons currently stored. */
  int GetNHardPartons() { return hp_list.size(); }

  /**
   * @brief Get a pointer to a hard parton at a given index.
   * @param i Index of the hard parton.
   * @return Shared pointer to the Parton.
   */
  shared_ptr<Parton> GetPartonAt(int i) { return hp_list[i]; }

  /**
   * @brief Access the list of all hard partons.
   * @return Reference to the vector of Parton shared pointers.
   */
  vector<shared_ptr<Parton>> &GetPartonList() { return hp_list; }

  /**
   * @brief Add a hard parton to the list.
   * @param p Shared pointer to a Parton object.
   */
  void AddParton(shared_ptr<Parton> p) { hp_list.push_back(p); }

  /**
   * @brief Retrieve the list of hard partons into an external vector.
   * @param plist Output vector of Parton shared pointers.
   */
  void GetHardPartonList(vector<shared_ptr<Parton>> &plist) { plist = hp_list; }

  /** @return Generated cross section (default = 1). */
  virtual double GetSigmaGen() { return 1; };

  /** @return Cross section error (default = 0). */
  virtual double GetSigmaErr() { return 0; };

  /** @return Generated pt-hat (default = 0). */
  virtual double GetPtHat() { return 0; };

  /** @return Event weight (default = 1). */
  virtual double GetEventWeight() { return 1; };

  /**
   * @brief Add a hadron to the list.
   * @param h Shared pointer to a Hadron object.
   */
  void AddHadron(shared_ptr<Hadron> h) { hd_list.push_back(h); }

  /**
   * @brief Retrieve the hadron list into an external vector.
   * @param hlist Output vector of Hadron shared pointers.
   */
  void GetHadronList(vector<shared_ptr<Hadron>> &hlist) { hlist = hd_list; }

  /** @return Reference to the internal list of Hadrons. */
  vector<shared_ptr<Hadron>> &GetHadronList() { return hd_list; }

  /** @return Number of hadrons currently stored. */
  int GetNHadrons() { return hd_list.size(); }

  /** @brief File name used for printing additional parton information. */
  std::string printer;

 private:
  /** @brief List of hard partons. */
  vector<shared_ptr<Parton>> hp_list;

  /** @brief List of hadrons generated by the hard process. */
  vector<shared_ptr<Hadron>> hd_list;
};

}  // end namespace Jetscape

#endif
